# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

# you can delete this line if you're not using Docker
# image: busybox:latest

before_script:
  - apt-get update
  - apt-get install gfortan
  - cd source
   
after_script:
  - make distclean
  - cd ..
   
build1:
  stage: build
  script:
    - make all